// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecocffjtlfttbmovpqnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjb2NmZmp0bGZ0dGJtb3ZwcW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzcxMjksImV4cCI6MjA2Mzg1MzEyOX0.pj0fPkcS-cUP3I55f4TG9tkD0hABKFgTJyUyPTIbnMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);